
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";



import ClientLayout from "./ClientLayout"
import Providers from "@/pages/_app";




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` ${geistSans.variable} ${geistMono.variable} antialiased`} data-theme="light">
 
        <Providers>
          <ClientLayout>
            {children}
          </ClientLayout>
        </Providers>
   
      </body>
    </html>
  );
}

export const metadata = {
  title: "EShop",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico", // general favicon
    shortcut: "/favicon.ico", // shortcut icon
    apple: "/apple-touch-icon.png", // Apple touch icon
  },
};
